import dotenv from 'dotenv';

dotenv.config();

type IEnv = {
  MONGO_URI: string;
  MONGO_URI_DEV: string;
  MONGO_URI_TEST: string;
  ORIGIN_DEV: string;
  ORIGIN: string;
  NODE_ENV: string;
  ACCESS_TOKEN_SECRET: string;
  REFRESH_TOKEN_SECRET: string;
  ACCESS_TOKEN_EXPIRATION: string;
  REFRESH_TOKEN_EXPIRATION: string;
  SMTP_SERVER: string;
  SMTP_USERNAME: string;
  SMTP_PASSWORD: string;
};

const {
  MONGO_URI,
  NODE_ENV,
  MONGO_URI_DEV,
  MONGO_URI_TEST,
  ORIGIN,
  ORIGIN_DEV,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRATION,
  REFRESH_TOKEN_EXPIRATION,
  SMTP_SERVER,
  SMTP_USERNAME,
  SMTP_PASSWORD,
} = process.env as IEnv;

const PORT = parseInt(process.env.PORT || '5000', 10);

export {
  MONGO_URI_DEV,
  MONGO_URI_TEST,
  MONGO_URI,
  ORIGIN_DEV,
  ORIGIN,
  NODE_ENV,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRATION,
  REFRESH_TOKEN_EXPIRATION,
  SMTP_SERVER,
  SMTP_USERNAME,
  SMTP_PASSWORD,
  PORT,
};
